### ISSUE TITLE
Child theme style missing

### ISSUE THREAD

**Issue by priteshparmar1092** [rtCamp/rtpanel-child-theme#7]
I am using the child theme along with rtpanel and the style appears to be broken when activating the child theme. Also the style.css is empty?
Can you please let me know if we need to build style from scratch?

**Comment by sagarjadhav** [comment]
Hello priteshparmar1092,

Thanks for point out this. I have just updated rtPanel child theme.
Please download and check again.
Feel free to create issue.
Thanks

**Comment by priteshparmar1092** [comment]
Thanks, now its working.
